### ISSUE TITLE
"Import Error: deformable_aggregation_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol" when I tried to train 

### ISSUE THREAD

**Issue by Slonna** [HorizonRobotics/Sparse4D#11]
ImportError: /home/xxx/code/Sparse4D/projects/mmdet3d_plugin/ops/deformable_aggregation_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv

**Comment by Slonna** [comment]
from .blocks import DeformableFeatureAggregation as DFG
  File "/home/sl/code/Sparse4D/projects/mmdet3d_plugin/models/blocks.py", line 26, in <module>
    from ..ops import deformable_aggregation_function as DAF
  File "/home/sl/code/Sparse4D/projects/mmdet3d_plugin/ops/__init__.py", line 3, in <module>
    from .deformable_aggregation import DeformableAggregationFunction
  File "/home/sl/code/Sparse4D/projects/mmdet3d_plugin/ops/deformable_aggregation.py", line 4, in <module>
    from . import deformable_aggregation_ext
ImportError: /home/sl/code/Sparse4D/projects/mmdet3d_plugin/ops/deformable_aggregation_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv

**Comment by xuanxuanxie** [comment]
hello, have u solved this problem?? If so, can u tell me how to solve it ?  Thank u!!! 
''' deformable_aggregation_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv  '''

**Comment by GrLynn12** [comment]
hello, have u solved this problem?? If so, can u tell me how to solve it ? Thank u!!!
