### ISSUE TITLE
Res101 config and nuImage pretrained config

### ISSUE THREAD

**Issue by NaomiEX** [HorizonRobotics/Sparse4D#12]
Hi, I was wondering whether there are any plans to release the R101 config and ckpt sometime soon?

Also, for both the Sparse4Dv2 and Sparse4Dv3 R101 pretrained with nuImage, is the only change to the config the pretrained R101 or are there other modifications necessary to recreate the results?

**Comment by linxuewu** [comment]
We don't plan to release more models.

For resnet101, you can try to set batch_size=2, lr=3e-4, epoch=80, backbone_lr_mult=0.1.

**Comment by zhaoyangwei123** [comment]
您好，如果设置batch_size=2, num_gpus=8，那么total batch size就从R50的48变成16是吗？
我的配置如下：otal_batch_size = 16　batch_size=2, num_gpus=8, num_iters_per_epoch = int(28130 // (num_gpus * batch_size))，lr=3e-4, epoch=80, backbone_lr_mult=0.1，想问一下这么配置的话和您所说的是一样的吗？

**Comment by Son-Goku-gpu** [comment]
Hi @linxuewu, thanks for your information. With your given paramters, we can boost sparse4d_v3 to a mAP of ~51.6% (almost approaching your released mAP 53.7%) with resnet101. May I know how we can further align our precision to yours? would you like to your release more details or show a fine-tuning direction to us? any help would be appreciated!

**Comment by shuaizg** [comment]
> Hi [@linxuewu](https://github.com/linxuewu), thanks for your information. With your given paramters, we can boost sparse4d_v3 to a mAP of ~51.6% (almost approaching your released mAP 53.7%) with resnet101. May I know how we can further align our precision to yours? would you like to your release more details or show a fine-tuning direction to us? any help would be appreciated!

Hi, could you share your training config? Thanks!
