### ISSUE TITLE
quality metric

### ISSUE THREAD

**Issue by DanielZ98** [HorizonRobotics/Sparse4D#13]
why is the yawness' label whether the predicted box and ground truth are acute angles [yns_target ](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/detection3d/losses.py#L81), rather than the cosine similarity of the predicted box and the groud truth box as written in the article?

**Comment by DanielZ98** [comment]
> The paper contains an error here. Thank you for bringing it to our attention.
Thank you for your response. I’m still somewhat puzzled as to why ‘whether it is an acute angle’ is being used as the truth label. Could you kindly shed some light on this?

**Comment by linxuewu** [comment]
The main goal is to reduce outliers with very large orientation errors.
For example, cases where vehicles with opposite direction or pedestrians' orientations sway left and right.
That's why we use classification labels instead of regression labels, which may have higher training noise.

**Comment by DanielZ98** [comment]
> The main goal is to reduce outliers with very large orientation errors. For example, cases where vehicles with opposite direction or pedestrians' orientations sway left and right. That's why we use classification labels instead of regression labels, which may have higher training noise.

I got it, thank you!
