### ISSUE TITLE
Regarding Engineering Applications

### ISSUE THREAD

**Issue by WxlSky** [HorizonRobotics/Sparse4D#17]
Thank you for sharing such an excellent work. Do you consider the engineering work of this algorithm? Which chip of Horizon can well support the application of this algorithm? Looking forward to your reply.

**Comment by linxuewu** [comment]
Sparse4D was actually developed for practical engineering purposes.
We have already deployed Sparse4D on Horizon's J5 and J6 chips.
The main engineering deployment will be on the J6.

**Comment by WxlSky** [comment]
That's fantastic! To deploy applications on the J5 or J6, will there be a need for further engineering optimization of the algorithm? What is the current inference time on J5?

**Comment by linxuewu** [comment]
The algorithm itself doesn't need optimization, but we need to trim down the model size. The trimmed model can achieve real-time inference speed.

**Comment by WxlSky** [comment]
That's great！thank you for your response.
