### ISSUE TITLE
The Json format of the log file is damaged

### ISSUE THREAD

**Issue by Son-Goku-gpu** [HorizonRobotics/Sparse4D#19]
Please check the json format of the log of sparse4d v2 with backbone resnet50 as it seems damaged, can you upload a correct one? Thanks.

**Comment by linxuewu** [comment]
https://github.com/linxuewu/Sparse4D/releases/download/v0.0/sparse4dv2_r50_HInf_256x704.log.json

**Comment by linxuewu** [comment]
This link can be opened on my end.

**Comment by Son-Goku-gpu** [comment]
Hi @linxuewu Thanks for your prompt reply, I tried to parse your json content with the tool http://json.parser.online.fr while failed again (SyntaxError: Unexpected non-whitespace character after JSON at position 19113 (line 2 column 1)), can you also have a try?

**Comment by linxuewu** [comment]
Each line in the file is one JSON object. Therefore, direct JSON parsing is not feasible.
`[json.loads(x) for x in open("file_path").read().strip().split("\n")]`

You only need to open it with any text reader. The first line contains configuration, while the lines below contain losses.

**Comment by Son-Goku-gpu** [comment]
@linxuewu Hi, I wrote a program to parse your json file with env & config parts as below
[sparse4dv2_r50_HInf_256x704.log](https://github.com/HorizonRobotics/Sparse4D/files/14478919/sparse4dv2_r50_HInf_256x704.log), while I found there exists some difference between your log and given config & requirements file, e.g., mmdete3d version and some config parameters. Actually, I failed to reproduce your mAP with your given config and requirements.txt, so will it caused by those difference? Thanks.

**Comment by linxuewu** [comment]
The mmdet3d version needs to be >=1.0.0rc. Besides mmdet3d, are there any other parameters that are different? Also, how much difference is there in the reproduced metrics? @linxuewu

**Comment by linxuewu** [comment]
And, to reproduce sparse4dv2, you can search in [the previous repository](https://github.com/linxuewu/Sparse4D/issues?q=is%3Aissue+is%3Aclosed) to see if there are similar issues that can be referenced.

**Comment by Son-Goku-gpu** [comment]
Thanks @linxuewu, I can reproduce your v2 results now. Also, I believe the batch_size might be one of important factors and may cause 10-points fluctuation in dist_train.

**Comment by linxuewu** [comment]
10-point descent, did NaN occur during training? 

> Thanks @linxuewu, I can reproduce your v2 results now. Also, I believe the batch_size might be one of important factors and may cause 10-points fluctuation in dist_train.
