### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by YoushaaMurhij** [HorizonRobotics/Sparse4D#21]
Hi, thanks  for sharing this great work! 
I want to run this model in inference mode on a custom dataset of **3** cameras.  I have mutlipe questions related to data preparation:
- Does the `projection_mat` in the dataloader contains `lidar2img` after considering the `T_global` transform or before it?
- If so, could you please refer to the part of code that do this?
- Do I need to change any parameter in the config except for `num_cams` in `deformable_model`?

**Comment by linxuewu** [comment]
The projection_mat is equivalent to `lidar2img`, it is the transformation matrix from 3D space to 2D pixels within a single frame, independent of `T_global`.
No need to modify anything else except `num_cams`.

**Comment by YoushaaMurhij** [comment]
Thanks for your fast response!

**Comment by YoushaaMurhij** [comment]
@linxuewu, I got very poor results compared to StreamPETR. I think it's the preprocessing step.
Could you please tell what are the necessary augmentation steps for inference? I used almost the same preprocessing as in StreamPETR.

**Comment by linxuewu** [comment]
> @linxuewu, I got very poor results compared to StreamPETR. I think it's the preprocessing step. Could you please tell what are the necessary augmentation steps for inference? I used almost the same preprocessing as in StreamPETR.

Is it directly using the checkpoint I provided for inference on the 3-camera dataset?
It's hard to say why this metric is deteriorating; it could be a normal phenomenon.
I suggest first using the [visualization code](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/utils.py#L207) to check if the trend of the inference results is roughly normal and ensure there are no bugs.

**Comment by YoushaaMurhij** [comment]
Yes, I am using your checkpoint and config.
I tried the visualization code. And it shows some objects on the first two frames and nothing after that. So I think its something related to the projection and global pose matrices. Exactly the same data and setup seems to work fine with streampetr.
I tried another code to visualize bev boxes and it shows some boxes but nothing on images. I need to figure out how to modify the projection mat for visualization.

**Comment by linxuewu** [comment]
It sounds like `T_global` and `T_global_inv` are not correct.

> Yes, I am using your checkpoint and config. I tried the visualization code. And it shows some objects on the first two frames and nothing after that. So I think its something related to the projection and global pose matrices. Exactly the same data and setup seems to work fine with streampetr. I tried another code to visualize bev boxes and it shows some boxes but nothing on images. I need to figure out how to modify the projection mat for visualization.

**Comment by edwardnguyen1705** [comment]
Hi @YoushaaMurhij ,
Have you resolved the issue?
