### ISSUE TITLE
report a eval bug

### ISSUE THREAD

**Issue by Son-Goku-gpu** [HorizonRobotics/Sparse4D#23]
Hi @linxuewu, I pulled the latest "main" branch code and tried to eval the pre-trained model, while meeting a bug as below:
![image](https://github.com/HorizonRobotics/Sparse4D/assets/59384638/c35e6bea-4f3f-4605-8f86-5b7c6351b730)

my command is "bash local_test.sh sparse4dv3_temporal_r50_1x8_bs6_256x704 /data/nuscenes/sparse4D/sparse4dv3_r50.pth", can you take a look at it?

**Comment by Son-Goku-gpu** [comment]
I have fixed this issue, thanks.

**Comment by wofeifeileni** [comment]
@Son-Goku-gpu Hi, I have also encountered the same problem. How did you solve it? Thank you
