### ISSUE TITLE
AssertionError: loss log variables are different across GPUs!

### ISSUE THREAD

**Issue by Slonna** [HorizonRobotics/Sparse4D#25]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/77110903/b14cd4c3-178d-4d68-bfa5-def0194c4939)
![微信图片_20240318085040](https://github.com/HorizonRobotics/Sparse4D/assets/77110903/3333d063-7b49-4cf8-bede-f1deeb386a61)

I met the error at the 87159 iter of 281820 iters.

It seems that the loss at this iter has no dn_loss as previous iter ,which lead to this error.

however, I don't know how to solve it?

**Comment by Slonna** [comment]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/77110903/40d7c567-3b06-4569-a03e-3f08849b3560)
This is the normal loss item.

**Comment by SheffieldCao** [comment]
> ![image](https://private-user-images.githubusercontent.com/77110903/313519105-40d7c567-3b06-4569-a03e-3f08849b3560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjU1NTQsIm5iZiI6MTcxMDc2NTI1NCwicGF0aCI6Ii83NzExMDkwMy8zMTM1MTkxMDUtNDBkN2M1NjctM2IwNi00NTY5LWEwM2UtM2YwODg0OWIzNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEyMzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZmM1ZTg0OTY2NDBhYzEyMDIyZjEzZDc0YjU2NGM1ZjdhOGJjNmU2NDAzMDcwYzgzZTY5NGIyYjFjYmM1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C2-oOs2IGCdw_fA1JWliGM_jYQyAxL0U1eHb0ALQBeY) This is the normal loss item. ( I am trying reproduce the sparse4dv3_r101 performance with the information you mentioned in the last issue. )

Same problem on 8xRTX3090.

**Comment by linxuewu** [comment]
It's possible that there are no ground truths in the same batch, which resulted in an error.

**Comment by Slonna** [comment]
So can I just comment this line in the code to refrain from this error. Or Is there any other way to refrain from this error ?
```python
        if dist.is_available() and dist.is_initialized():
            log_var_length = torch.tensor(len(log_vars), device=loss.device)
            dist.all_reduce(log_var_length)
            message = (f'rank {dist.get_rank()}' +
                       f' len(log_vars): {len(log_vars)}' + ' keys: ' +
                       ','.join(log_vars.keys()))
            ## here is the bug reason
            assert log_var_length == len(log_vars) * dist.get_world_size(), \
                'loss log variables are different across GPUs!\n' + message
```

**Comment by linxuewu** [comment]
https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/detection3d/target.py#L176-L177

Try commenting out these two lines of code.

**Comment by feimadada** [comment]
> https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/detection3d/target.py#L176-L177
> 
> Try commenting out these two lines of code.

Does this commenting affect training results?

**Comment by feimadada** [comment]
> https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/detection3d/target.py#L176-L177
> 
> Try commenting out these two lines of code.

注释掉这两行之后会报其他错误
<img width="482" alt="image" src="https://github.com/user-attachments/assets/b3447693-ad74-4db5-a182-b7d3610b3cd8">

**Comment by feimadada** [comment]
> So can I just comment this line in the code to refrain from this error. Or Is there any other way to refrain from this error ?
> 
> ```python
>        # anaconda3/envs/sparse4dv3_sl/lib/python3.8/site-packages/mmdet/models/detectors/base.py
>         if dist.is_available() and dist.is_initialized():
>             log_var_length = torch.tensor(len(log_vars), device=loss.device)
>             dist.all_reduce(log_var_length)
>             message = (f'rank {dist.get_rank()}' +
>                        f' len(log_vars): {len(log_vars)}' + ' keys: ' +
>                        ','.join(log_vars.keys()))
>             ## here is the bug reason
>             assert log_var_length == len(log_vars) * dist.get_world_size(), \
>                 'loss log variables are different across GPUs!\n' + message
> ```

hello,does this commenting work?

**Comment by feimadada** [comment]
> > So can I just comment this line in the code to refrain from this error. Or Is there any other way to refrain from this error ?
> > ```python
> >        # anaconda3/envs/sparse4dv3_sl/lib/python3.8/site-packages/mmdet/models/detectors/base.py
> >         if dist.is_available() and dist.is_initialized():
> >             log_var_length = torch.tensor(len(log_vars), device=loss.device)
> >             dist.all_reduce(log_var_length)
> >             message = (f'rank {dist.get_rank()}' +
> >                        f' len(log_vars): {len(log_vars)}' + ' keys: ' +
> >                        ','.join(log_vars.keys()))
> >             ## here is the bug reason
> >             assert log_var_length == len(log_vars) * dist.get_world_size(), \
> >                 'loss log variables are different across GPUs!\n' + message
> > ```
> 
> hello,does this commenting work?

I met the same problem https://github.com/open-mmlab/mmdetection/issues/9340#issuecomment-1544975881

**Comment by clmforgit** [comment]
```python
# target.py  get_dn_anchors
        if max_dn_gt == 0:  
            # return None  
            max_dn_gt = 1
``` 

```python
# sparse4d_head.py loss
            # cls_loss = self.loss_cls(
            #     cls.flatten(end_dim=1)[dn_valid_mask],
            #     dn_cls_target,
            #     avg_factor=num_dn_pos,
            # )
            if torch.sum(dn_valid_mask) == 0:
                cls_loss = torch.tensor(0).type_as(output[f"{self.task_prefix}_loss_cls_0"])
            else:
                cls_loss = self.loss_cls(
                    cls.flatten(end_dim=1)[dn_valid_mask],
                    dn_cls_target,
                    avg_factor=num_dn_pos,
                )
```
