### ISSUE TITLE
运行bash local_test.sh出错

### ISSUE THREAD

**Issue by wofeifeileni** [HorizonRobotics/Sparse4D#27]
您好，运行验证命令时出现错误，似乎是提示CUDA不可用，我的环境里已经按照要求安装了torch==1.13.0+cu116，请问如何解决，十分感谢。
![2024-03-21 00-15-29 的屏幕截图](https://github.com/HorizonRobotics/Sparse4D/assets/126314381/2b292d1a-76d1-4238-bd04-a70f964129e2)

**Comment by linxuewu** [comment]
local_test里面指定了CUDA_VISIBLE_DEVICES=3，看看有没有这张卡或者是不是这张卡被占满了。

**Comment by wofeifeileni** [comment]
只有一张卡，设置CUDA_VISIBLE_DEVICES=1，仍然出现以上问题

**Comment by linxuewu** [comment]
只有一张卡，CUDA_VISIBLE_DEVICES应该设为0.

**Comment by wofeifeileni** [comment]
成功解决了，感谢
