### ISSUE TITLE
Data_aug_conf of 640*1600 resolution 

### ISSUE THREAD

**Issue by 504058568** [HorizonRobotics/Sparse4D#28]
Thanks you for your excellent work. When I try to train the model using the following data_aug_conf, due to the number of gt being 0, the dn_metas is None, which result in inconsistent loss lengths during multi card training and an error message. Can you provide the data_aug_conf configuration of the resolution 640 * 1600?
```
data_aug_conf = {
        "resize_lim": (0.94, 1.25),
        "final_dim": (640, 1600),
        "bot_pct_lim": (0.0, 0.0),
        "rot_lim": (-5.4, 5.4),
        "H": 900,
        "W": 1600,
        "rand_flip": True,
        "rot3d_range": [-0.3925, 0.3925],
    }
```

**Comment by linxuewu** [comment]
'Inconsistent loss lengths' and 'data aug config' are unrelated. Try commenting out these two lines of code？

https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/detection3d/target.py#L176-177

**Comment by 504058568** [comment]
```
  File "/home/wh/Sparse4Dv3/projects/mmdet3d_plugin/models/detection3d/target.py", line 234, in get_dn_anchors
    cost = box_cost[i].cpu().numpy()
AttributeError: 'NoneType' object has no attribute 'cpu'
```
I commented out these two lines of code, but it still reported an error. I don't know the relationship between 'Inconsistent loss lengths' and 'data aug config', but I am certain that 'Inconsistent loss lengths' are due to one of the gpus not outputting the set of loss_dn. This issue does not occur when I use the config with resolution 256 * 704, could you please provide a config with resolution 640 * 1600?

**Comment by linxuewu** [comment]
image size increases --> the batch size decreases  --> some batches without ground truth  --> dn_meta=None.

**Comment by linxuewu** [comment]
This is a bug introduced when I organized the code before open-sourcing it.

Please modify it according to the following, and try again.
![image](https://github.com/HorizonRobotics/Sparse4D/assets/50012935/97af2103-f2ca-4662-8f56-63d9a52f2a24)

**Comment by RYHSmmc** [comment]
@linxuewu hello, when training Sparese4D-v3, I change the resolution 640 * 1600, but get lower mAP then 320*800, any other setting is fixed, can you give me some advice?

**Comment by 504058568** [comment]
> This is a bug introduced when I organized the code before open-sourcing it.
> 
> Please modify it according to the following, and try again. ![image](https://private-user-images.githubusercontent.com/50012935/315975365-97af2103-f2ca-4662-8f56-63d9a52f2a24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTMzMzEsIm5iZiI6MTcxMTk1MzAzMSwicGF0aCI6Ii81MDAxMjkzNS8zMTU5NzUzNjUtOTdhZjIxMDMtZjJjYS00NjYyLThmNTYtNjNkOWE1MmYyYTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA2MzAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGFhNmQ2MDk4ZGU5MDk2ZmVkMDA1Y2Y4ODI2YjhhYjJkMzA0NWU5NzI3YWE0NDEwNDRmMWM2NzliMDM2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gGQtJo4Qnh51Jh9qupog48chImxejDfFpKY18v_9nFE)

Thank you for your help, but this still reports an error. I modified the following code and it runs normally, but I am not sure if it will affect accuracy.
https://github.com/HorizonRobotics/Sparse4D/blob/8cde8d1015a8908081ba049fccc5c2594780b06f/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py#L240C1-L249C20
`    def __getitem__(self, idx):
        while True:
            if isinstance(idx, dict):
                aug_config = idx["aug_config"]
                idx = idx["idx"]
            else:
                aug_config = self.get_augmentation()
            data = self.get_data_info(idx)
            data["aug_config"] = aug_config
            data = self.pipeline(data)
            if not self.test_mode and len(data['gt_bboxes_3d']) == 0:
                idx = self._rand_another(idx)
                continue
            return data

    def _rand_another(self, idx):
        """Randomly get another item with the same flag.

        Returns:
            int: Another index of item with the same flag.
        """
        pool = np.where(self.flag == self.flag[idx])[0]
        return np.random.choice(pool)`

**Comment by happygds** [comment]
> def _rand_another(self, idx):
>         """Randomly get another item with the same flag.
> 
>         Returns:
>             int: Another index of item with the same flag.
>         """
>         pool = np.where(self.flag == self.flag[idx])[0]
>         return np.random.choice(pool)

Hi, how do you solve this error when the GPU memory is limited? Could you give a brief description?

**Comment by happygds** [comment]
> image size increases --> the batch size decreases --> some batches without ground truth --> dn_meta=None.

Hi, how do you solve this error when the GPU memory is limited? Could you give a brief description?

**Comment by 504058568** [comment]
> > image size increases --> the batch size decreases --> some batches without ground truth --> dn_meta=None.
> 
> Hi, how do you solve this error when the GPU memory is limited? Could you give a brief description?

Modify the code I mentioned, it works for me.
