### ISSUE TITLE
I wanna visualize the deformable aggregation module

### ISSUE THREAD

**Issue by tyloocifer** [HorizonRobotics/Sparse4D#30]
Thanks for your excellent work! I'm trying to visualize the key_points sampled from anchor and make sure that they were in the place that i want it to be. i believe that u had done a lot of work like this. Would you mind plz tell me how to do that? thank u!

**Comment by linxuewu** [comment]
The evaluation stage has a visual interface, just remove the comment from [this line of code](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py#L639). Then, it is necessary to pass the [key_points](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/models/blocks.py#L121) to the dataset and use the [draw_points_on_img](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/utils.py#L130) in the [show](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py#L639) function to draw the key_points on the images.
