### ISSUE TITLE
Confusing Anchor Generation

### ISSUE THREAD

**Issue by Son-Goku-gpu** [HorizonRobotics/Sparse4D#32]
Hi @linxuewu, Thanks for the generous open-source code. Here I'd like to share an issue confusing me a lot. 
In the paper of sparse4D v1, the authors state as below (W(1), L(1), H(1), Sin_YAW (0), Cos_YAW (1)):
![image](https://github.com/HorizonRobotics/Sparse4D/assets/59384638/075d129a-c6e1-4838-be85-020a15d328cf).
When I read nuscenes_kmeans900.npy downloaded by the hyperlink provided in https://github.com/linxuewu/Sparse4D ('main' branch),
![image](https://github.com/HorizonRobotics/Sparse4D/assets/59384638/717aa04f-fdce-40f5-a421-764440ab493c) and found W(1), L(1), H(1), Sin_YAW (1), Cos_YAW (0) as below:
![image](https://github.com/HorizonRobotics/Sparse4D/assets/59384638/156ac61e-32f8-4eba-8dc4-f46057a81f84).
So, it's easy to conclude that the provided .npy is different from the paper statement and also the generation code for Cos_YAW & Sin_YAW.

Furthermore, the code https://github.com/HorizonRobotics/Sparse4D/blob/main/tools/anchor_generator.py#L25 shows W, L, H are also calculated based on kmeans results, which is different from the provided .npy (W/L/H=1/1/1).

With these differences, can you help to clarify them? Thanks.

**Comment by linxuewu** [comment]
The prior values of these different anchors are similar, and using any of them yields almost the same performance.

There's not much of difference.
