### ISSUE TITLE
Sparse4D-v3-offline

### ISSUE THREAD

**Issue by lmb633** [HorizonRobotics/Sparse4D#33]
你好，请问下在训练的时候如何将未来帧加进来？

**Comment by linxuewu** [comment]
用sparse4dv1那种多帧采样的方式，在未来帧采样特征。

**Comment by lmb633** [comment]
非常感谢回复。还是有一点不太清楚，时序融合方式是完全按照sparse4dv1的方式进行融合的吗，那样

**Comment by linxuewu** [comment]
历史帧还是采用v2的recurrent的方式，只有未来帧用多帧采样。

**Comment by lmb633** [comment]
好的，明白了，非常感谢！
