### ISSUE TITLE
question about fix_scale

### ISSUE THREAD

**Issue by WeiSQ-zju** [HorizonRobotics/Sparse4D#34]
作者你好，我理解的13个关键点是由7个固定关键点加6个可学习的关键点一起组成的，其中7个固定关键点是由fix_scale配置的，fix_scale应该为[[0, 0, 0],[0.45, 0, 0],[-0.45, 0, 0], [0, 0.45, 0],[0, -0.45, 0], [0, 0, 0.45],[0, 0, -0.45],]，但是我发现fix_scale的值并不是配置值，而是在Sparse4DHead的init_weights函数中被重新初始化了，请问这是个bug吗？

**Comment by tyloocifer** [comment]
I also found out that problem.

**Comment by linxuewu** [comment]
多谢提醒，这确实是个bug，应该是开源之前整理代码的时候引入的。
在原本代码中fix_scale是np.ndarray [link](https://github.com/HorizonRobotics/Sparse4D/blob/v2.0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L134)，不存在这个问题，开源代码之前我改成nn.parameter了，导致出了问题。

**Comment by feimadada** [comment]
> 多谢提醒，这确实是个bug，应该是开源之前整理代码的时候引入的。 在原本代码中fix_scale是np.ndarray [link](https://github.com/HorizonRobotics/Sparse4D/blob/v2.0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L134)，不存在这个问题，开源代码之前我改成nn.parameter了，导致出了问题。

v2版本的代码是正确的，但是v3版本的代码还没有修复这个bug

**Comment by feimadada** [comment]
> > 多谢提醒，这确实是个bug，应该是开源之前整理代码的时候引入的。 在原本代码中fix_scale是np.ndarray [link](https://github.com/HorizonRobotics/Sparse4D/blob/v2.0/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L134)，不存在这个问题，开源代码之前我改成nn.parameter了，导致出了问题。
> 
> 这个bug目前在主分支里面没有改吗？
看到了，sparse4d v2 版本是正确的           self.fix_scale = np.array(fix_scale)
        fix_scale = anchor.new_tensor(self.fix_scale)

**Comment by frothmoon** [comment]
@linxuewu @feimadada @WeiSQ-zju @tyloocifer @hlnull   大家好，抱歉打扰，请问修复了这个问题以后，模型有获得性能上的提升吗？
