### ISSUE TITLE
val error

### ISSUE THREAD

**Issue by CYYAI** [HorizonRobotics/Sparse4D#36]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/32134215/b249ab8a-296f-4672-846b-9b43c86abb1a)

**Comment by linxuewu** [comment]
Has the training diverged? You can debug to see if there are any NaN values in the model's output layer?

**Comment by CYYAI** [comment]
Using the model you gave me, and then infer directly

**Comment by linxuewu** [comment]
The checkpoint weights did not load correctly.
![image](https://github.com/HorizonRobotics/Sparse4D/assets/50012935/e5d6f949-ecb5-431c-a032-31745f173b6c)
