### ISSUE TITLE
我想要使用deformable attention替代DAF

### ISSUE THREAD

**Issue by tyloocifer** [HorizonRobotics/Sparse4D#38]
我想要使用deformable attention替代DAF看一下效果如何，我的reference points应该是anchor中心点的坐标吗？还有 我应该是先加上偏移量再进行投影还是先进行投影再加上偏移量呢？

**Comment by tyloocifer** [comment]
anchor中心点投影到图像上之后，有的值非常奇怪，远远超出了坐标范围，导致我无法将anchor中心点作为reference poins进行计算。请问您当时做过与deformable attention的对比吗

**Comment by linxuewu** [comment]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/50012935/978ab261-f396-46a5-8b44-7179d6b207fa)
DAG是deformable aggregation，DAT是deformable attention。
先用中心点投影到各个图上拿到reference points，然后预测2d offset和weights，对各个视角进行deformable attetion，最后把各个视角的结果加权平均一下。不过这个实验有点久远了，细节记得不是很清楚。

**Comment by linxuewu** [comment]
投影不到图像上是正常情况，这些点得到的特征也是全0。
