### ISSUE TITLE
Is it easy to deploy Sparse4D in NvidiaOrin?

### ISSUE THREAD

**Issue by wutheringcoo** [HorizonRobotics/Sparse4D#39]
Hi, Do you test latency of the model with config: Res50 + 256x704?
if the speed is too slowly, how to change sparse4D to sparse3d(it can alse support end2end track&detection),  and performance metric will drop significantly？

**Comment by linxuewu** [comment]
We have not tried to deploy sparse4d to orin, only to the horizon journey series chips. There is not much difference in inference speed between sparse4d and sparse3d (single-frame model), and sparse3d cannot achieve end-to-end tracking.
See the paper for the inference speed of the GPU and the performance of the single-frame model.
