### ISSUE TITLE
模型head中有几层调用的是DeformableFeatureAggregation算子动态库，该模型如何转换onnx呢？

### ISSUE THREAD

**Issue by wutheringcoo** [HorizonRobotics/Sparse4D#40]
请问下像是这种层结构（调用DAF动态库）如何转onnx呢？
from ..ops import deformable_aggregation_function as DAF
features = DAF(*feature_maps, points_2d, weights).reshape(
                bs, num_anchor, self.embed_dims
            )

**Comment by linxuewu** [comment]
把use_deformable_func关了，用grid_sample代替。
