### ISSUE TITLE
如何得到最适配的bbox?

### ISSUE THREAD

**Issue by A-fei-yang** [HorizonRobotics/Sparse4D#41]
我在使用您们的代码进行视频推理时，发现最终输出的检测结果中，会对一个目标形成多个框，请问如何选取最佳的框，针对每一个检测目标只选择一个最佳的框？使用的是tutorial中的代码，在阅读test以及tutorial中推理源码时，似乎没有对最终结果进一步处理选择最佳的框。感谢您的回复

**Comment by linxuewu** [comment]
one2one匹配的检测算法都没有框的后处理（如NMS），直接卡一个较高的阈值就能将大部分重复框去掉。如果想完全摆脱重复框，可以考虑加上3d nms。
