### ISSUE TITLE
bbox追踪不稳定的问题

### ISSUE THREAD

**Issue by zhui064** [HorizonRobotics/Sparse4D#45]
我用了自己的 7v数据集训练 sparse4D v3，模型输出的检测结果正常，但是追踪很不稳定，总是丢失目标。从3d bbox 渲染结果看，框的颜色一直在变化。可能是什么原因呢？（复现过 nuscenes数据的结果，追踪是很稳定的）

**Comment by linxuewu** [comment]
首先训练一定要充分，需要在检测优化得比较好的后，再多训一段时间跟踪指标才能提升上来。不同数据集可能需要不同的训练超参数，比如cost weight之内的。

**Comment by CMSC740Student** [comment]
@linxuewu 

I observe a very similar problem. What do u recommend when we notice ID switch for objects very close to each other? Which parameter can be tweaked?

In my dataset, objects further away from one another have very good tracking performance.

**Comment by coco401** [comment]
> [@linxuewu](https://github.com/linxuewu)
> 
> I observe a very similar problem. What do u recommend when we notice ID switch for objects very close to each other? Which parameter can be tweaked?
> 
> In my dataset, objects further away from one another have very good tracking performance.

have you solove this problem?
