### ISSUE TITLE
convergence of dn loss

### ISSUE THREAD

**Issue by zhui064** [HorizonRobotics/Sparse4D#49]
I train on my custom dataset.  The total loss fluctuated.  I found it's because **loss_box_dn_1 ~ loss_box_dn_5** fluctuated, but all  other loss decline steadily.
When I disable dn_loss in config, the training loss decline steadily.    So why did dn_loss not work in my dataset?  How to fix it ?

![image](https://github.com/HorizonRobotics/Sparse4D/assets/32017746/17dac9ee-266a-42e9-88d4-334f33e2d6b1)

![image](https://github.com/HorizonRobotics/Sparse4D/assets/32017746/3d599814-0e1b-4f49-8542-517a8acbefe3)

**Comment by linxuewu** [comment]
I haven't encountered this situation. 

I don't know the status of your private dataset and can't tell what the problem is.

**Comment by AWDawson** [comment]
@zhui064 Hi，I also encountered this problem. Could you tell me how you fix it?

**Comment by zengstrive** [comment]
> @zhui064 Hi，I also encountered this problem. Could you tell me how you fix it?

Hello, have you fixed this problem
