### ISSUE TITLE
cls and Dn loss nan

### ISSUE THREAD

**Issue by Gaondong** [HorizonRobotics/Sparse4D#50]
Thanks for your excellent work. I closed the depth estimation branch but encountered cls loss nan and dn loss nan in 38000+ iters.
![image](https://github.com/HorizonRobotics/Sparse4D/assets/43692998/a15da4a1-a247-402d-ba69-e1955ee8f703)
`optimizer = dict(
    type="AdamW",
    lr=2e-4,
    weight_decay=0.001,
    paramwise_cfg=dict(
        custom_keys={
            "img_backbone": dict(lr_mult=0.5),
        }
    ),
)`

**Comment by linxuewu** [comment]
Reducing the batch size or disabling the depth auxiliary task both require reducing the learning rate. You need to further decrease the learning rate.

**Comment by Gaondong** [comment]
> Reducing the batch size or disabling the depth auxiliary task both require reducing the learning rate. You need to further decrease the learning rate.

My batchsize is 64, the learningrate is set to 4e-4 at first, it is reduced to 2e-4, and the NAN still appears, do I need to adjust it to 1e-4

**Comment by linxuewu** [comment]
Is the dataset you are using the nuScenes dataset?

**Comment by Gaondong** [comment]
> Is the dataset you are using the nuScenes dataset?
It's not nuscenes, it's custom dataset.

**Comment by linxuewu** [comment]
I can't determine the cause of the problem, because there are too many influencing factors.

**Comment by Gaondong** [comment]
I'll try to reduce the learning rate. Thanks.




------------------ Original ------------------
From: linxuewu ***@***.***&gt;
Date: Fri,May 24,2024 8:02 PM
To: HorizonRobotics/Sparse4D ***@***.***&gt;
Cc: jiandong.gao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [HorizonRobotics/Sparse4D] cls and Dn loss nan (Issue #50)

**Comment by zengstrive** [comment]
Hello, how did you solve this problem.

**Comment by Gaondong** [comment]
> Hello, how did you solve this problem.

learningrate 减低到1e-4看起来能收敛，如果还有问题，可以尝试再减小。

**Comment by zengstrive** [comment]
> > Hello, how did you solve this problem.
> 
> learningrate 减低到1e-4看起来能收敛，如果还有问题，可以尝试再减小。

谢谢回复！6e-5是一个不错的选择，模型已经收敛了。
