### ISSUE TITLE
How do I get a visualization of the tracking

### ISSUE THREAD

**Issue by flora077** [HorizonRobotics/Sparse4D#51]
Hello, I specialize in multi-object tracking. In sparse4d_v3, I understand that there seems to be no need for modifications during the training phase, and that ID assignment is only necessary during the inference stage. I want to know where this is reflected, and how I should visualize the tracking results, like a video sequence with 3D boxes labeled with IDs.

**Comment by linxuewu** [comment]
Open this line for visualization. https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/configs/sparse4dv3_temporal_r50_1x8_bs6_256x704.py#L456

**Comment by flora077** [comment]
thank u very much！
