### ISSUE TITLE
AssertionError: Sparse4D: Sparse4DHead: DeformableFeatureAggregation: deformable_aggregation needs to be set up.

### ISSUE THREAD

**Issue by flora077** [HorizonRobotics/Sparse4D#52]
I encountered the following error.
![image](https://github.com/HorizonRobotics/Sparse4D/assets/94901804/7d49fc71-3dbe-4495-85a3-58bdc186cbcd)

I strictly followed your quick_start.md, but an error occurred during training:: AssertionError: Sparse4D: Sparse4DHead: DeformableFeatureAggregation: deformable_aggregation needs to be set up.

**Comment by flora077** [comment]
我在配置文件中看到了
![image](https://github.com/HorizonRobotics/Sparse4D/assets/94901804/7047c0fc-9aaf-4384-89cd-3b55fb609630)
但是我确实已经执行了mmdet3d_plugin/ops/setup.py

**Comment by linxuewu** [comment]
应该时没编译好。明确下面两点：mmdet3d_plugin/ops里面有编译好的so文件了吗？直接import 能成功么？

**Comment by flora077** [comment]
1、在ops中有编译好的so文件
2、在终端中输入import deformable_aggregation_function as DAF，会报错：No module named 'deformable_aggregation_function'
所以我在想是不是应该设置什么路径？但是我不知道应该如何设置...

**Comment by flora077** [comment]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/94901804/4092d948-1ace-4aa5-86e4-93af86fcd95e)

**Comment by flora077** [comment]
好吧，我把ops文件夹中的内容全部删除，替换成新的后再编译，问题就消失了

**Comment by feimadada** [comment]
你好，请问你最后说的这个把ops文件夹中的内容全部删除，替换成新的，是替换成哪里的？
