### ISSUE TITLE
temporal parameter in the config file

### ISSUE THREAD

**Issue by commc** [HorizonRobotics/Sparse4D#56]
你好，林博，感谢您的出色工作，我有几个关于config文件中temporal参数的问题，我使用的config是[sparse4dv3_temporal_r50_1x8_bs6_256x704.py](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/configs/sparse4dv3_temporal_r50_1x8_bs6_256x704.py)，只对temporal参数进行了修改：
（1）如果我不想在模型中引入历史帧，只想做单帧的训练和推理，是不是只用更改config文件中的temporal=True ---> temporal=False？
（2）我设置temporal=False进行训练后，用相同的config文件进行测试报出以下错误，如果我想实现（1）怎么进行正确的设置呢？：
![EOkMQtPB3H](https://github.com/HorizonRobotics/Sparse4D/assets/143334124/f85da8f6-f2df-48f6-80ca-0052a19302a3)

**Comment by linxuewu** [comment]
单帧模型不支持多目标跟踪，get_instance_id的时候有个bug导致的。代码修改了。https://github.com/HorizonRobotics/Sparse4D/commit/911318c7eb5e32af6427673d3e10e65eb2bae01d

**Comment by linxuewu** [comment]
另外单帧模型的话，可以把tracking_test也给置为False.

**Comment by commc** [comment]
感谢答疑！
