### ISSUE TITLE
Centerness and Yawness Loss

### ISSUE THREAD

**Issue by CeZh** [HorizonRobotics/Sparse4D#57]
Hello, according to the paper, it seems like you are using cross-entropy on yawness, and focal loss on centerness. While in the open-source code [configs](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/configs/sparse4dv3_temporal_r50_1x8_bs6_256x704.py#L286), it seems like you are using focal loss on yawness and cross-entropy on centerness. Can you clarify which is the correct way to compute these losses? Thanks a lot! Below is a screenshot from sparse4D v3 paper.
![image](https://github.com/HorizonRobotics/Sparse4D/assets/41165430/aa20c246-06d1-4286-9c5f-322ee410a42f)

**Comment by linxuewu** [comment]
The code takes precedence. 

There is an error in the writing of this part of the paper. Apologies for any confusion caused.

**Comment by CeZh** [comment]
That totally makes sense now. Thanks a lot! I also re-opened a [previous issue (issue 48)](https://github.com/HorizonRobotics/Sparse4D/issues/48) and asked a few more questions. If you have time, would you please also help me to solve those issues? Thanks
