### ISSUE TITLE
How to adjust the detection range？

### ISSUE THREAD

**Issue by WangMeng-daw** [HorizonRobotics/Sparse4D#58]
Nice work! I got 0.39mAP in range 0-50m , but only 0mAP in range 50-100m . Can I adjust detection range by changing "--detection_range" in file named anchor_generator.py  when initializing anchors? Or there is another way? Thank you !

**Comment by linxuewu** [comment]
In addition to modifying the anchor, the loss weight also needs to be adjusted. 

For a 100m perception range, it is recommended to set the regression loss weight for xyz to 1. 

Additionally, for different datasets, parameters such as the learning rate may also need to be adjusted.
