### ISSUE TITLE
not use depth supervision, will the model  work?

### ISSUE THREAD

**Issue by northeastsquare** [HorizonRobotics/Sparse4D#6]
In config file, if not use depth supervision, will the model  work?

  depth_branch=dict(  # for auxiliary supervision only
        type="DenseDepthNet",
        embed_dims=embed_dims,
        num_depth_layers=num_depth_layers,
        loss_weight=0.2,
    ),

**Comment by linxuewu** [comment]
Dense depth supervise is not necessary, but it's useful for imporving training stability. If dense depth supervision is removed, the learning rate should be appropriately reduced.

**Comment by SuperPengXue** [comment]
Why not do an ablation experiment without use depth supervision?
