### ISSUE TITLE
时序dn相关问题：没有instance_inds，就没法train时序dn相关的loss了吗

### ISSUE THREAD

**Issue by zhhy1999** [HorizonRobotics/Sparse4D#62]
![temp_dn](https://github.com/HorizonRobotics/Sparse4D/assets/151845354/5dbf067f-cc34-430d-aadc-cfd4648c89d5)

**Comment by linxuewu** [comment]
是的，时序dn需要依赖id。不过去掉时序dn对指标影响不大。

**Comment by commc** [comment]
可以请教下，在时序训练的时候如何去掉时序dn呢？

**Comment by linxuewu** [comment]
https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/configs/sparse4dv3_temporal_r50_1x8_bs6_256x704.py#L254

**Comment by linxuewu** [comment]
把这个参数置为-1

**Comment by commc** [comment]
> 把这个参数置为-1

感谢感谢！
