### ISSUE TITLE
Reproduce Result Seems Slightly Lower than Tab. 3 

### ISSUE THREAD

**Issue by MandyMo** [HorizonRobotics/Sparse4D#63]
I found that the results (training from scratch with resnet-50 backbone with 8X A100 GPU) seems to be slight lower than that presented in Tab. 3.  The logs of the evaluation process are listed as bellow,

[res50-retrain.json](https://github.com/user-attachments/files/16049908/res50-retrain.json)

**Comment by linxuewu** [comment]
https://github.com/HorizonRobotics/Sparse4D/issues/8

**Comment by MandyMo** [comment]
> #8

Thanks for your reply.
