### ISSUE TITLE
sparse4d resnet101，img_size=[512, 1408]的配置，理论上可以在24G的4090上运行吗？

### ISSUE THREAD

**Issue by HuiAuto** [HorizonRobotics/Sparse4D#69]
我尝试使用sparse4d resnet101，img_size=[512, 1408]的配置训练sparse4d，但结果显示torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 274.00 MiB (GPU 0; 23.62 GiB total capacity; 20.95 GiB already allocated; 58.38 MiB free; 21.19 GiB reserved in total by PyTorch) 。
这表明21.19G的显存依然是不足的。那么请问在您实验的时候使用sparse4d resnet101，img_size=[512, 1408]的配置训练sparse4d，占用显存在23G以内吗？24G的4090理论上可以使用sparse4d resnet101，img_size=[512, 1408]的配置训练sparse4d吗？

**Comment by linxuewu** [comment]
把batch size调小就行了，单卡batch size=3应该能训起来。同时learning rate和resize_lim也需要做相应的调整。
