### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by wofeifeileni** [HorizonRobotics/Sparse4D#7]
Hi, thank you for your excellent work. Will the project provide code for visualizing the predicted results in the future？

**Comment by linxuewu** [comment]
The code for visualization is already available. Just uncomment this [line](https://github.com/HorizonRobotics/Sparse4D/blob/main/projects/configs/sparse4dv3_temporal_r50_1x8_bs6_256x704.py#L456) in the config to enable visualization. Run `bash local_test.sh config path/to/checkpoint` and the results will be saved in the `out_dir`.

**Comment by wofeifeileni** [comment]
Thank you for your careful answer.
