### ISSUE TITLE
Regarding Training on custom dataset

### ISSUE THREAD

**Issue by shubhendu-ranadive** [HorizonRobotics/Sparse4D#72]
Hello,

Thank you for the great work on Spatio-Temporal 3D-OD models.

I have a small and maybe naive question about training Sparse4Dv3 on custom dataset.
I have lots of camera frames in my sequential dataset that do not contain any target object for detection (for example, NuScenes classes). While training the model on this dataset, should those frames be removed or be kept as it is, since the model uses information from previous frames?

**Comment by linxuewu** [comment]
Frames without targets can be retained during training. However, it depends on their proportion; if the proportion is too high, it will affect the model's performance.

**Comment by andrew403** [comment]
Hello, I am also trying to use my own dataset for training, what parameters do I need to contain in the dataset? Duing the inference, what part of the parameters are being used? I am struggling on this problem recently, so if you know anything would be helpful to me. Thank you.

**Comment by shubhendu-ranadive** [comment]
Hello @andrew403 

By parameters, do you mean the contents of the arguments that are being passed during inference?

**Comment by shubhendu-ranadive** [comment]
I will close this issue for now since I don't have more questions at the moment. Feel free to comment on this if anyone has questions.
