### ISSUE TITLE
跟踪评估报错

### ISSUE THREAD

**Issue by flora077** [HorizonRobotics/Sparse4D#78]
林博好，我在test的过程中，目标检测可以正常评估如图1，虽然结果不好，但是我认为这是训练参数的问题。但是跟踪部分无法正常进行评估如图2，请问这是为什么，期待您的回复
![image](https://github.com/user-attachments/assets/a4818ace-b7de-43fd-af1c-3178d01fa9f4)
![image](https://github.com/user-attachments/assets/2a2b7d03-c030-4d87-9ab7-46567561705b)

**Comment by linxuewu** [comment]
这个问题我也遇到过，似乎当检测指标比较低的情况下发生的概率比较大，如果检测指标高基本不会有这个问题。

具体原因我也没分析过，我怀疑是不是某些帧出现了一个instance id对应多个prediction bbox的情况。

**Comment by flora077** [comment]
好的 那看来还是要提升检测的指标 感谢您的回复
