### ISSUE TITLE
请教个关于tracking的问题

### ISSUE THREAD

**Issue by owphoo** [HorizonRobotics/Sparse4D#83]
你好，我看代码加了一个衰减参数保证Temporal的anchor能够尽可能传到下一帧，但是是怎么保证在下一帧中它能够继续传递，而不是由下一帧的top 300个anchor中产生?
因为非temporal的部分也是正常产生所有的检测，取topk后也是基本上是当帧所有的检测，
temp_gnn是如何保证最后输出的结果是从temporal的600个而不是当前top k的300个anchor产生？    
我的理解是通过与temporal anchor做cross attention达到隐式去除？但这一部分并没有做一些监督，是如何做到的？

**Comment by linxuewu** [comment]
这是一个优化问题，temporal anchor的质量远优于currrent anchor，训练中temporal instance匹配上的概率就会远大于current instance，使得它能稳定跟踪上。而且temporal feature和current feature具备显著差异，所以网络能很轻松的判断哪些是temporal传过来的。cross attention提供了一部分temporal的信息，但不是主要原因。
