### ISSUE TITLE
fix_scale的设置

### ISSUE THREAD

**Issue by lanyouzibetty** [HorizonRobotics/Sparse4D#84]
`林博士，你好！请问在生成固定keypoints时，为什么fix_scale每个面只有一维有值，而且是0.45呢？
`fix_scale=[  [0, 0, 0],
                    [0.45, 0, 0],
                    [-0.45, 0, 0],
                    [0, 0.45, 0],
                    [0, -0.45, 0],
                    [0, 0, 0.45],
                    [0, 0, -0.45],
                ],`

**Comment by owphoo** [comment]
@lanyouzibetty 应该是假设object中心是 (x, y, z), size是(l, w, h)，a_i, b_i, c_i是fix_scale，
那么这7个点就是(x, y, z) + （a_i * l, b
_i * w, c_i * h），分别就是object中心和object6个面的中心（不是严格中心，取0.45是往object的长方体里面缩一些）

**Comment by lanyouzibetty** [comment]
@owphoo 谢谢网友的回答，确实更想了解0.45的设置考虑，这样有助于减少由于边界效应引起的误差，提升目标检测和跟踪的性能
