### ISSUE TITLE
Sparse4D-v1导出onnx模型时遇torch报错 ’Couldn't lower all tuples‘

### ISSUE THREAD

**Issue by reskipper** [HorizonRobotics/Sparse4D#85]
Sparse4D-v1，使用requirement.txt中的环境配置，通过在`mmdetection3d/mmdet3d/apis/test.py`构建model wrapper尝试导出onnx模型，修改如下
```class ModelWrapper(torch.nn.Module):
    def __init__(self, model, data):
        super(ModelWrapper, self).__init__()
        self.model = model
        self.img_metas = data['img_metas']
        self.timestamp = data['timestamp']
        self.projection_mat = data['projection_mat']
        self.image_wh = data['image_wh']

    def forward(self, img):

        img = DataContainer([img])

        data = {'img_metas': self.img_metas, 'img': img,
                'timestamp': self.timestamp, 'projection_mat': self.projection_mat,
                'image_wh': self.image_wh}
        result = self.model(return_loss=False, rescale=True, **data)

        boxes_3d = result[0]['img_bbox']['boxes_3d']
        scores_3d = result[0]['img_bbox']['scores_3d']
        labels_3d = result[0]['img_bbox']['labels_3d']

        return boxes_3d, scores_3d, labels_3d

def single_gpu_test(model,
                    data_loader,
                    show=False,
                    out_dir=None,
                    show_score_thr=0.3):                    

…………

    for i, data in enumerate(data_loader):
        with torch.no_grad():

            model_wrapper = ModelWrapper(model, data)

            # output = model_wrapper(data['img'].data[0])  # 能够跑通推理

            # 导出ONNX
            example_input = data['img'].data[0]
            torch.onnx.export(model_wrapper, example_input, 'Sparse4D-v1.onnx', verbose=True, input_names=['input'], output_names=['boxes_3d', 'scores_3d', 'labels_3d'])
```
遇到报错
```
Traceback (most recent call last):
  File "tools/test.py", line 315, in <module>
    main()
  File "tools/test.py", line 258, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "~/repo/Sparse4D/mmdetection3d/mmdet3d/apis/test.py", line 77, in single_gpu_test
    torch.onnx.export(model_wrapper, example_input, 'Sparse4D-v1.onnx', verbose=True, input_names=['input'], output_names=['boxes_3d', 'scores_3d', 'labels_3d'])
  File ~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "~/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "~/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 151, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: Couldn't lower all tuples.
```
求助，感谢！

**Comment by BigTeacher-777** [comment]
> Sparse4D-v1，使用requirement.txt中的环境配置，通过在`mmdetection3d/mmdet3d/apis/test.py`构建model wrapper尝试导出onnx模型，修改如下
> 
> ```
>     def __init__(self, model, data):
>         super(ModelWrapper, self).__init__()
>         self.model = model
>         self.img_metas = data['img_metas']
>         self.timestamp = data['timestamp']
>         self.projection_mat = data['projection_mat']
>         self.image_wh = data['image_wh']
> 
>     def forward(self, img):
> 
>         img = DataContainer([img])
> 
>         data = {'img_metas': self.img_metas, 'img': img,
>                 'timestamp': self.timestamp, 'projection_mat': self.projection_mat,
>                 'image_wh': self.image_wh}
>         result = self.model(return_loss=False, rescale=True, **data)
> 
>         boxes_3d = result[0]['img_bbox']['boxes_3d']
>         scores_3d = result[0]['img_bbox']['scores_3d']
>         labels_3d = result[0]['img_bbox']['labels_3d']
> 
>         return boxes_3d, scores_3d, labels_3d
> 
> def single_gpu_test(model,
>                     data_loader,
>                     show=False,
>                     out_dir=None,
>                     show_score_thr=0.3):                    
> 
> …………
> 
>     for i, data in enumerate(data_loader):
>         with torch.no_grad():
> 
>             model_wrapper = ModelWrapper(model, data)
> 
>             # output = model_wrapper(data['img'].data[0])  # 能够跑通推理
> 
>             # 导出ONNX
>             example_input = data['img'].data[0]
>             torch.onnx.export(model_wrapper, example_input, 'Sparse4D-v1.onnx', verbose=True, input_names=['input'], output_names=['boxes_3d', 'scores_3d', 'labels_3d'])
> ```
> 
> 遇到报错
> 
> ```
> Traceback (most recent call last):
>   File "tools/test.py", line 315, in <module>
>     main()
>   File "tools/test.py", line 258, in main
>     outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
>   File "~/repo/Sparse4D/mmdetection3d/mmdet3d/apis/test.py", line 77, in single_gpu_test
>     torch.onnx.export(model_wrapper, example_input, 'Sparse4D-v1.onnx', verbose=True, input_names=['input'], output_names=['boxes_3d', 'scores_3d', 'labels_3d'])
>   File ~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "~/miniconda3/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
>     _model_to_graph(model, args, verbose, input_names,
>   File "~/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
>     graph = _optimize_graph(graph, operator_export_type,
>   File "~/envs/sparse4d-v1.0-v2/lib/python3.8/site-packages/torch/onnx/utils.py", line 151, in _optimize_graph
>     torch._C._jit_pass_lower_all_tuples(graph)
> RuntimeError: Couldn't lower all tuples.
> ```
> 
> 求助，感谢！

你好，我遇到了同样的问题，请问你解决了吗，咋整的

**Comment by reskipper** [comment]
@BigTeacher-777 这个报错我通过注释掉 test.py 里的 MMDataParallel 调用解决的，像这样
```python
 elif not distributed:
        # model = MMDataParallel(model, device_ids=[0])
        outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
```

**Comment by BigTeacher-777** [comment]
> @BigTeacher-777 这个报错我通过注释掉 test.py 里的 MMDataParallel 调用解决的，像这样
> 
> ```python
>  elif not distributed:
>         # model = MMDataParallel(model, device_ids=[0])
>         outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
> ```

嗯嗯你说的这个我之前试过，会报另一个错AttributeError: 'DataContainer' object has no attribute “shape”，你遇到过吗？或者说是否方便留个联系方式我们交流下

**Comment by BigTeacher-777** [comment]
> > @BigTeacher-777 这个报错我通过注释掉 test.py 里的 MMDataParallel 调用解决的，像这样
> > ```python
> >  elif not distributed:
> >         # model = MMDataParallel(model, device_ids=[0])
> >         outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
> > ```
> 
> 嗯嗯你说的这个我之前试过，会报另一个错AttributeError: 'DataContainer' object has no attribute “shape”，你遇到过吗？或者说是否方便留个联系方式我们交流下

我尝试把DataContainer注释掉这个问题没有了，后面会报torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tile' to ONNX opset version 11 is not supported

**Comment by reskipper** [comment]
@BigTeacher-777 你可以试试指定opset version。可以的，vx：skippershih

**Comment by JYS997760473** [comment]
> @BigTeacher-777 你可以试试指定opset version。可以的，vx：skippershih

请问指定opset version多少呢

**Comment by JYS997760473** [comment]
> > > @BigTeacher-777 这个报错我通过注释掉 test.py 里的 MMDataParallel 调用解决的，像这样
> > > ```python
> > >  elif not distributed:
> > >         # model = MMDataParallel(model, device_ids=[0])
> > >         outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
> > > ```
> > 
> > 
> > 嗯嗯你说的这个我之前试过，会报另一个错AttributeError: 'DataContainer' object has no attribute “shape”，你遇到过吗？或者说是否方便留个联系方式我们交流下
> 
> 我尝试把DataContainer注释掉这个问题没有了，后面会报torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::tile' to ONNX opset version 11 is not supported

请问现在转onnx成功了吗
