### ISSUE TITLE
How to determine `num_iters_per_epoch`?

### ISSUE THREAD

**Issue by yizhou-wang** [HorizonRobotics/Sparse4D#87]
Thanks a lot for the open-source project! 

I'm training the model on a customized dataset but how should I determine `num_iters_per_epoch` in the config file? 

In the default config:
```
num_iters_per_epoch = int(28130 // (num_gpus * batch_size))
```
What is 28130 here? And how to get this number on my customized dataset?

Thanks for the help in advance!

**Comment by feimadada** [comment]
28130 is the trainset frame num
