### ISSUE TITLE
dn_cls_target初始化问题

### ISSUE THREAD

**Issue by Xiang95** [HorizonRobotics/Sparse4D#9]
你好，我想问一下为什么在SparseBox3DTarget 的 get_dn_anchors 函数中为什么要将dn_cls_target初始化为-3？
![企业微信截图_17070131045308](https://github.com/HorizonRobotics/Sparse4D/assets/27827152/7067fd7e-cf72-4c71-afc3-8052cd399c88)

**Comment by linxuewu** [comment]
这就是一个标志位，比如-1的标志位表示pad，这里的-3是为了表示那些没匹配上的dn instance，-2的标志位在开源的代码里面没用到所以删了。

**Comment by Xiang95** [comment]
> 这就是一个标志位，比如-1的标志位表示pad，这里的-3是为了表示那些没匹配上的dn instance，-2的标志位在开源的代码里面没用到所以删了。
感谢感谢，我这边还有个问题，这个地方为什么要把cls_target >=0 & dn_cls_target==-3的部分放在valid_mask里面呢？
![企业微信截图_17070258422079](https://github.com/HorizonRobotics/Sparse4D/assets/27827152/98319bbf-3d92-4ae1-bfd7-099ad176290f)

**Comment by linxuewu** [comment]
`cls_target >=0 & dn_cls_target==-3`表示那些没匹配上而且不是padding的框，为dn的负样本，需要加入训练。 @Xiang95
